[project]
name = "cs50-web"
version = "0.1.0"
description = "A collection of my solutions to the problem sets of Harvard's CS50-web"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "check50>=3.3.11",
    "django>=5.2.3",
    "markdown2>=2.5.3",
    "submit50>=3.2.0",
]
