# Generated by Django 5.2.3 on 2025-06-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listings_category_delete_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='category_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
